// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletApi.Data;

#nullable disable

namespace WalletApi.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260627203817_AddMultiCurrency")]
    partial class AddMultiCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletApi.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Code");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(3560),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "US Dollar",
                            Symbol = "$",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(3560)
                        },
                        new
                        {
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4400),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "Euro",
                            Symbol = "€",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410)
                        },
                        new
                        {
                            Code = "GBP",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "British Pound",
                            Symbol = "£",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410)
                        },
                        new
                        {
                            Code = "SAR",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "Saudi Riyal",
                            Symbol = "﷼",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410)
                        },
                        new
                        {
                            Code = "AED",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "UAE Dirham",
                            Symbol = "د.إ",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410)
                        },
                        new
                        {
                            Code = "JPY",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410),
                            DecimalPlaces = 0,
                            IsActive = true,
                            Name = "Japanese Yen",
                            Symbol = "¥",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410)
                        },
                        new
                        {
                            Code = "BTC",
                            CreatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4410),
                            DecimalPlaces = 8,
                            IsActive = true,
                            Name = "Bitcoin",
                            Symbol = "₿",
                            UpdatedAt = new DateTime(2026, 6, 27, 20, 38, 17, 405, DateTimeKind.Utc).AddTicks(4420)
                        });
                });

            modelBuilder.Entity("WalletApi.Entities.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(28,10)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("ToCurrency");

                    b.HasIndex("FromCurrency", "ToCurrency");

                    b.HasIndex("FromCurrency", "ToCurrency", "CreatedAt");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("WalletApi.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(28,0)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<long>("PayableId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayableType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("WalletId");

                    b.HasIndex("PayableType", "PayableId");

                    b.HasIndex("PayableType", "PayableId", "Confirmed");

                    b.HasIndex("PayableType", "PayableId", "Type");

                    b.HasIndex("PayableType", "PayableId", "Type", "Confirmed");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WalletApi.Entities.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DepositId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(28,0)")
                        .HasDefaultValue(0m);

                    b.Property<JsonDocument>("Extra")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Fee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(28,0)")
                        .HasDefaultValue(0m);

                    b.Property<long>("FromId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Transfer");

                    b.Property<string>("StatusLast")
                        .HasColumnType("text");

                    b.Property<long>("ToId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<long>("WithdrawId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DepositId")
                        .IsUnique();

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("WithdrawId")
                        .IsUnique();

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("WalletApi.Entities.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(28,0)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("HolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("HolderType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Currency");

                    b.HasIndex("Slug");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("HolderType", "HolderId", "Slug")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("WalletApi.Entities.ExchangeRate", b =>
                {
                    b.HasOne("WalletApi.Entities.Currency", "From")
                        .WithMany("FromRates")
                        .HasForeignKey("FromCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WalletApi.Entities.Currency", "To")
                        .WithMany("ToRates")
                        .HasForeignKey("ToCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("WalletApi.Entities.Transaction", b =>
                {
                    b.HasOne("WalletApi.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletApi.Entities.Transfer", b =>
                {
                    b.HasOne("WalletApi.Entities.Transaction", "Deposit")
                        .WithOne("DepositTransfer")
                        .HasForeignKey("WalletApi.Entities.Transfer", "DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletApi.Entities.Wallet", "From")
                        .WithMany("SentTransfers")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WalletApi.Entities.Wallet", "To")
                        .WithMany("ReceivedTransfers")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WalletApi.Entities.Transaction", "Withdraw")
                        .WithOne("WithdrawTransfer")
                        .HasForeignKey("WalletApi.Entities.Transfer", "WithdrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");

                    b.Navigation("From");

                    b.Navigation("To");

                    b.Navigation("Withdraw");
                });

            modelBuilder.Entity("WalletApi.Entities.Wallet", b =>
                {
                    b.HasOne("WalletApi.Entities.Currency", "CurrencyInfo")
                        .WithMany("Wallets")
                        .HasForeignKey("Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrencyInfo");
                });

            modelBuilder.Entity("WalletApi.Entities.Currency", b =>
                {
                    b.Navigation("FromRates");

                    b.Navigation("ToRates");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("WalletApi.Entities.Transaction", b =>
                {
                    b.Navigation("DepositTransfer");

                    b.Navigation("WithdrawTransfer");
                });

            modelBuilder.Entity("WalletApi.Entities.Wallet", b =>
                {
                    b.Navigation("ReceivedTransfers");

                    b.Navigation("SentTransfers");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
